### ISSUE TITLE
unclosed quote in line causing corrupted TAMUIC DwC-A accessed via SCAN

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/tamuic-ent#2]
From review report of TAMUIC-ENT obtained from SCAN, I noticed that the last record (starting with ```12825572 | TAMU | ENTO |   | 13b264e0-ea1c-4ff2-8229-0507f8dbf46a | Preserved specimen``` appears to be chopped off and contains an un-closed quoted string:

```12825572,TAMU,ENTO,,13b264e0-ea1c-4ff2-8229-0507f8dbf46a,"Preserved specimen",039a4013-7e83-4d31-9950-6d8890256307,X0922022,,Animalia,Arthropoda,Insecta,Hemiptera,Miridae,Taedia,202418,"Distant, 1883",Taedia,,,,,,,,,,,"Schaffner, J. C.",,1987-05-20,1987,5,20,140,141,05/20/1987,,,,,,,,,,adult,,,,,,"United States of America",Texas,"Jim Wells",,"8 miles W Ben Bolt, La Copita Research Station",,27.64753,-98.21186,NAD27,,,"D. Allen Dean","named place/site + distance/direction","BioGeomancer Workbench","georeferencing complete",,,,,,,,,,,"2013-08-22 11:17:54",http://creativecommons.org/licenses/by-nc/3.0/,"Texas A&M University","```

Notice the last ```,"``` : the un-closed string quote.

Here's a table with other records that seems to suggest that the last record somehow got chopped off.

modified | rights | rightsHolder | accessRights | recordId
-- | -- | -- | -- | --
2013-08-22 11:17:54 | http://creativecommons.org/licenses/by-nc/3.0/ | Texas A&M University | Not-for-profit use only | urn:uuid:f8464158-1808-49a7-ab94-80a6f89439fd
2013-08-22 11:17:54 | http://creativecommons.org/licenses/by-nc/3.0/ | Texas A&M University | Not-for-profit use only | urn:uuid:4cc76f0d-9093-4d28-a9d7-4239c560bfa9
2013-08-22 11:17:54 | http://creativecommons.org/licenses/by-nc/3.0/ | Texas A&M University | Not-for-profit use only | urn:uuid:41481eaf-2de0-4959-a3d1-36567bf19405
2013-08-22 11:17:54 | http://creativecommons.org/licenses/by-nc/3.0/ | Texas A&M University | Not-for-profit use only | urn:uuid:403ae2b8-ab4d-4c75-8ca9-a595e7670905
2013-08-22 11:17:54 | http://creativecommons.org/licenses/by-nc/3.0/ | Texas A&M University | Not-for-profit use only | urn:uuid:9ad4e938-3fd4-484a-b4f3-01272d12ded3
2013-08-22 11:17:54 | http://creativecommons.org/licenses/by-nc/3.0/ | Texas A&M University | Not-for-profit use only | urn:uuid:86f07d46-75e1-4861-89ac-13fb772e55b7
2013-08-22 11:17:54 | http://creativecommons.org/licenses/by-nc/3.0/ | Texas A&M University | Not-for-profit use only | urn:uuid:4751d555-ee62-4acc-9bf5-fc70714de606
2013-08-22 11:17:57 | http://creativecommons.org/licenses/by-nc/3.0/ | Texas A&M University | Not-for-profit use only | urn:uuid:2be11d02-50d0-4e9f-b806-c94a5aa342a5
2013-08-22 11:17:54 | http://creativecommons.org/licenses/by-nc/3.0/ | Texas A&M University | Not-for-profit use only | urn:uuid:f0ca067a-8b7d-4ccb-bc68-52df34df8a97
2013-08-22 11:17:54 | http://creativecommons.org/licenses/by-nc/3.0/ | Texas A&M University |   |  

@seltmann @neilcobb any idea why the record for TAMUIC is getting chopped off?

**Comment by neilcobb** [comment]
no, they use an institutional database and upload a csv periodically.  So it could have happened at a couple of different points along the way.

**Comment by jhpoelen** [comment]
@neilcobb thanks for your quick response. 

@seltmann I was thinking to send an email to john oswald, but was wondering whether it'd be easier to include this in your ongoing conversation with John. don't want to distract him more than necessary.

**Comment by jhpoelen** [comment]
Please advise.

**Comment by neilcobb** [comment]
If it was on their end Ed Riley is the person to engage, maybe Karen but she seems overwhelmed these days

**Comment by seltmann** [comment]
@jhpoelen I am working with Karen right now for a new data export from the TAMU database. If we can get a list of these issues together, I can communicate those to her.

Ed is not working with the database any longer.

**Comment by jhpoelen** [comment]
Good to hear that you are working with Karen. This un-closed quote issue is the only one I am aware of. If I find more, I'll open additional issues. I am assuming that no action is needed on my end and that the updated data export will be automatically picked-up by GloBI as soon as it is available via SCAN.

**Comment by neilcobb** [comment]
Karen already knows about the GBIF issue that has been pending for about a year or so

**Comment by seltmann** [comment]
@jhpoelen yes, should be and hopefully will include interactions!

**Comment by seltmann** [comment]
@jhpoelen for clarification. You are getting the data from the SCAN darwin core archive? The issue with the open quote then is from SCAN, not from TAMU

**Comment by jhpoelen** [comment]
ok, I've updated the issue title in an attempt to clarify the origin of the tamuic archive. Please feel free to change if needed, you should have edit rights.

**Comment by neilcobb** [comment]
Karen just emailed me to say that she wants to solve both problems together in two weeks……..

**Comment by seltmann** [comment]
@neilcobb The downloaded csv file from SCAN for TAMU is only 235,961 rows, but it is listed that the TAMU collection has 548,589 occurrences on SCAN. I suggest the issue *might* be something going on in SCAN, not the data supplied by TAMU, where the creation of the text (occurrences.txt) file is being cut short?

Separate issue perhaps, but I also noticed that some of the larger Darwin Core archive zips are also not available through SCAN (FMNH-FMNHINS DwC-Archive) with a web message saying file not found.

**Comment by neilcobb** [comment]
I downloaded 548,589 records a month ago, I have them and TAMU has a copy.

I have no Idea why FMNH was listed, I removed it and about 15 other collections that SCAN should not be serving

**Comment by jhpoelen** [comment]
The plot thickens . . . I was able to get 

```
$ unzip TAMU-TAMUIC_DwC-A.zip 
Archive:  TAMU-TAMUIC_DwC-A.zip
  inflating: occurrences.csv         
  inflating: identifications.csv     
  inflating: images.csv              
  inflating: meta.xml                
  inflating: eml.xml                 
$ wc -l occurrences.csv 
235961 occurrences.csv
``` 
235961 lines retrieved from https://scan-bugs.org:443/portal/content/dwca/TAMU-TAMUIC_DwC-A.zip .

**Comment by neilcobb** [comment]
I refreshed the archive, can you try again

**Comment by jhpoelen** [comment]
After refresh, I got:

```
$ unzip TAMU-TAMUIC_DwC-A.zip 
Archive:  TAMU-TAMUIC_DwC-A.zip
  inflating: occurrences.csv         
  inflating: identifications.csv     
  inflating: images.csv              
  inflating: meta.xml                
  inflating: eml.xml                 
$ wc -l occurrences.csv 
548586 occurrences.csv
```
what was the root cause of the incomplete archive?

**Comment by neilcobb** [comment]
I have no idea

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jhpoelen** [comment]
I re-ran the review of tamuic-ent via https://travis-ci.org/globalbioticinteractions/tamuic-ent/jobs/658439033#L217 and confirmed that the unclosed quote issue no longer occurs. 

@neilcobb thanks for refreshing the archive
